project_name: example
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: ["ghcr.io/caarlos0/goreleaser-docker-manifest-actions-example:{{ .Version }}-amd64"]
  binaries: [example]
  dockerfile: Dockerfile
  build_flag_templates: ["--build-arg", "ARCH=amd64"]
- image_templates: ["ghcr.io/caarlos0/goreleaser-docker-manifest-actions-example:{{ .Version }}-arm64v8"]
  binaries: [example]
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates: ["--build-arg", "ARCH=arm64v8"]
docker_manifests:
- name_template: ghcr.io/caarlos0/goreleaser-docker-manifest-actions-example:{{ .Version }}
  image_templates:
  - ghcr.io/caarlos0/goreleaser-docker-manifest-actions-example:{{ .Version }}-amd64
  - ghcr.io/caarlos0/goreleaser-docker-manifest-actions-example:{{ .Version }}-arm64v8
